### ISSUE TITLE
coordinate of exported mesh 

### ISSUE THREAD

**Issue by Runsong123** [19reborn/NeuS2#10]
Dear author, 

Thanks for your guidance, I can successfully run the method. However, I am a little confused about coordinate the exported mesh, which is inconsistent with the coordinate of extraced mesh by neus. Besides, could you please provide the code for the alignment with extracted mesh by neus methods for the evaluation.

Looking forward to your reply.

Bests,
Runsong

**Comment by erin47** [comment]
Hi,
Thanks a lot for your valuable suggestion. We will provide the evaluation script (including mesh transformation & Chamfer Distance evaluation) asap. Will let you know, once this has been completed.

**Comment by Runsong123** [comment]
> 

Got it. Thanks in advance. I really understand it takes time to prepare the whole precessing code. 

But if possible, could you please point the main differences the mesh coordinate extracted by current repo with the mesh coordinate extracted by Neus method. 

Anyway, thanks for your kind reply again. Cheers!

Bests,
Runsong

**Comment by Runsong123** [comment]
> Hi, Thanks a lot for your valuable suggestion. We will provide the evaluation script (including mesh transformation & Chamfer Distance evaluation) asap. Will let you know once this has been completed.

Got it. Thanks in advance. I really understand it takes time to prepare the whole precessing code.

But if possible, could you please point the main differences the mesh coordinate extracted by current repo with the mesh coordinate extracted by Neus method?

Anyway, thanks for your kind reply. Cheers!

Bests,
Runsong

**Comment by erin47** [comment]
Hi,
Inherited from the original NeuS's data preprocessing, we transform the scene to its local space by "scale_mat". So you need to transform the mesh back to world space, like https://github.com/Totoro97/NeuS/blob/629b9cf0d9e2451d10c498726b51a7940069ed13/exp_runner.py#L337 in NeuS.

**Comment by Runsong123** [comment]
> Hi, Inherited from the original NeuS's data preprocessing, we transform the scene to its local space by "scale_mat". So you need to transform the mesh back to world space, like https://github.com/Totoro97/NeuS/blob/629b9cf0d9e2451d10c498726b51a7940069ed13/exp_runner.py#L337 in NeuS.


Thanks! I will check it according to your reply. :)

Bests,
Runsong

**Comment by Runsong123** [comment]
> > Hi, Inherited from the original NeuS's data preprocessing, we transform the scene to its local space by "scale_mat". So you need to transform the mesh back to world space, like https://github.com/Totoro97/NeuS/blob/629b9cf0d9e2451d10c498726b51a7940069ed13/exp_runner.py#L337 in NeuS.
> 
> Thanks! I will check it according to your reply. :)
> 
> Bests, Runsong

Oh, I found the inconsistency is from the datasets. Actually, I use the dataset for Neus2 downloaded from IDR repo. However, (scale, translation) they are different from the released data from Neus. 
I just use the same dataset and then the mesh coordinate is the same as Neus results. So, I will close the issue. 
Thanks so much.

Bests,
Runsong

**Comment by Runsong123** [comment]
Dear author,

It seems I still need your evaluation protocol considering there may exist some specific post-processing. Actually, the calculated metric is 1.0052 instead of 0.7 in the paper when running the evaluation code in NeuralUDF.

BTW, I found the reconstructed mesh (e.g., scan24) contains some obvious artifacts, is it the expected results? 

![image](https://github.com/19reborn/NeuS2/assets/39645074/228299d6-bcb3-4aef-93bd-b16dc0cbaa1d)



Bests,
Runsong

**Comment by erin47** [comment]
Hi,
This result is not desirable, please check your configuration file (the lr should be 1e-2).

**Comment by Runsong123** [comment]
> should

Thanks for you reply.
I just follow you guidance to run the code and I assume that it should be the same setting as the experiment in paper. Do I need to change the configuration manually? Considering there are multiple 'lr' variables, it is a little confusing to me.

**Comment by erin47** [comment]
Hi,
I am sorry that my previous answer is not clear. Could you tell me what configuration you use for this result? Or, you can paste a copy of the configuration file here for me to check through.

btw, your current result is similar to the result given the default (base.json) configuration produced by my device.

**Comment by Runsong123** [comment]
Hi, actually I does not set the config path but it will use the base.json defaults from my understanding. Maybe I can just modify this code to load the dtu.json in the script/run.py, does that work? (https://github.com/19reborn/NeuS2/blob/main/scripts/run.py#L87C49-L87C53)

**Comment by erin47** [comment]
> understanding

Sure, you can have a try.

**Comment by Runsong123** [comment]
Yes, it looks much better now. Thanks.

<img width="653" alt="image" src="https://github.com/19reborn/NeuS2/assets/39645074/eb3c8a04-5566-417a-89d9-2f55925136bc">
