### ISSUE TITLE
Camera intrinsics and lens distortion

### ISSUE THREAD

**Issue by drperpen** [19reborn/NeuS2#13]
Hi,
After successfully running the  dtu_scan24 scene, I am trying to run a multi-camera single shot that I ran recently using instant-ngp. I see that the intrinsics matrix comes in a 4x4 form, and besides the usual fx,fy,cx,cy there is another value that I assume is s (skew).

My camera parameters comes from Agisoft Metashape (xml format) so I created a script (based on the one Nerfstudio provides) to convert from that to NeuS2 format. 

I am setting the s value to 0.0, and I am not getting good results, no convergence at all. My guess is that maybe that could improve if I could feed the lens distortion parameters (which I have in my xml) to NeuS2. As your code is partially based on instant-ngp, do you think there a is way to do that? If yes, could you please point me to the code part I should look into? Thanks a lot!

**Comment by 19reborn** [comment]
Hi, the original instant-ngp transform.json can be used in NeuS2. Have you tried directly using your instant-ngp data on NeuS2?

**Comment by drperpen** [comment]
Yes, and I get different but also not good results. One question, does NeuS2 always expect images with an alpha channel? I think that is the problem, my files don't have one.

**Comment by 19reborn** [comment]
Yes, Neus2 need background masks as the alpha channel.

**Comment by drperpen** [comment]
I created the masks and I didn't get good results either. Then I adjusted the offset (the area of interest was not at 0,0,0 of the metashape camera poses) and then everything worked good. Thanks!
