### ISSUE TITLE
Degenerated performance on shape 40 of DTU

### ISSUE THREAD

**Issue by Runsong123** [19reborn/NeuS2#14]
Dear author, 

Thanks for your great work. Here is the my evaluation metric on DTU.  I found that the performance is degenerated severely in shape#40. Is  the degeneration on Shape#40 expected?
Many thanks in advance.

![image](https://github.com/19reborn/NeuS2/assets/39645074/11762fa1-be75-41af-b0d4-b446929bdf22)

![image](https://github.com/19reborn/NeuS2/assets/39645074/c2a74258-2bec-439e-8a75-d60eb3dfcd5d)

![image](https://github.com/19reborn/NeuS2/assets/39645074/d2091536-2c2b-4b56-90a4-04913bd90e59)

Bests,
Runsong

**Comment by erin47** [comment]
Hi,
In our experiment, we set the eikonal loss weight https://github.com/19reborn/NeuS2/blob/055b39b9d4f76ddd6ef811ad5519426b6c8dd8ad/configs/nerf/dtu.json#L124 of scan40 to 0.001. Maybe you might consider experimenting with different hyperparameters for different scenes.

**Comment by Runsong123** [comment]
Got it. Since I wan to reproduce your result in my machine, would you mind sharing your experiments configuration for different scenes if you modify the hyperparameter from the default dtu.json?

Bests,
Runsong

**Comment by erin47** [comment]
Hi @Runsong123 ,
sorry for the late reply. This link https://drive.google.com/file/d/1DKXLkOHml6s5IB5yzn_HdYNv-ykGUJxr/view?usp=sharing contains the checkpoint and configuration file of each scan. Hope it helps!
