### ISSUE TITLE
 error: identifier "FullyFusedMLP" is undefined

### ISSUE THREAD

**Issue by Luh1124** [19reborn/NeuS2#15]
I encountered an error while executing "cmake --build build --config RelWithDebInfo -j":
Graphics card: 1080ti.
cuda：11.8
CUDA architectures: 61
(nerf) luh@lihong:~/repo1/repo_8T/code/1.nerf/NeuS2$ cmake --build build --config RelWithDebInfo -j
[  3%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/context.c.o
[  5%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/common_device.cu.o
[  7%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/monitor.c.o
[  3%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/common.cu.o
[  9%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/cpp_api.cu.o
[ 10%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/window.c.o
[ 12%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/init.c.o
[ 14%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/input.c.o
[ 16%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/vulkan.c.o
[ 18%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/cutlass_mlp.cu.o
[ 20%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/x11_init.c.o
[ 21%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/x11_monitor.c.o
[ 25%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/encoding.cu.o
[ 25%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/loss.cu.o
[ 29%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/object.cu.o
[ 29%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/network.cu.o
[ 30%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/x11_window.c.o
[ 32%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/optimizer.cu.o
[ 34%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/posix_time.c.o
[ 36%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/reduce_sum.cu.o
[ 38%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/xkb_unicode.c.o
[ 40%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/posix_thread.c.o
[ 41%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/glx_context.c.o
[ 43%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/egl_context.c.o
[ 45%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/osmesa_context.c.o
[ 47%] Building C object dependencies/glfw/src/CMakeFiles/glfw_objects.dir/linux_joystick.c.o
[ 47%] Built target glfw_objects
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(114): error: identifier "FullyFusedMLP" is undefined

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(114): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(114): error: the global scope has no "REQUIRED_ALIGNMENT"

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(115): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(115): error: the global scope has no "REQUIRED_ALIGNMENT"

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(116): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(116): error: the global scope has no "REQUIRED_ALIGNMENT"

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(117): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(117): error: the global scope has no "REQUIRED_ALIGNMENT"

9 errors detected in the compilation of "/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu".
make[2]: *** [dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/build.make:167: dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/network.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:254: dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by Luh1124** [comment]
However, during the compilation of instant-ngp, everything was normal except for the warning message "CMake Warning at dependencies/neus2_tcnn/CMakeLists.txt:114 (message): Fully fused MLPs do not support GPU architectures of 70 or less. Falling back to CUTLASS MLPs. Remove GPU architectures 70 and lower to allow maximum performance."

**Comment by 19reborn** [comment]
Hi @Luh1124 , Thanks for pointing out this error. I just updated a new commit for the `neus2_tcnn`. Could you please use the lateset version and try compiling it?

**Comment by wangjialuu** [comment]
> 

I got the same error. And already pull the newest commit for neus2_tcnn.

**Comment by luh0502** [comment]
> Hi @Luh1124 , Thanks for pointing out this error. I just updated a new commit for the `neus2_tcnn`. Could you please use the lateset version and try compiling it?

**I have pulled the latest version of the repository, but I still have the same error.**

(base) luh@lihong:~/repo1/repo_8T/code/1.nerf/NeuS2$ cmake --build build --config RelWithDebInfo -j
[ 29%] Built target glfw_objects
[ 30%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/optimizer.cu.o
[ 34%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/network.cu.o
[ 34%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/object.cu.o
[ 36%] Building CUDA object dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/reduce_sum.cu.o
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(114): error: identifier "FullyFusedMLP" is undefined

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(114): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(114): error: the global scope has no "REQUIRED_ALIGNMENT"

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(115): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(115): error: the global scope has no "REQUIRED_ALIGNMENT"

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(116): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(116): error: the global scope has no "REQUIRED_ALIGNMENT"

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(117): error: type name is not allowed

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu(117): error: the global scope has no "REQUIRED_ALIGNMENT"

9 errors detected in the compilation of "/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/dependencies/neus2_tcnn/src/network.cu".
make[2]: *** [dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/build.make:167: dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/network.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:254: dependencies/neus2_tcnn/src/CMakeFiles/tiny-cuda-nn.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by luh0502** [comment]
I tried deploying the environment on a 3090 and encountered a new error. **Could this be related to the version of OptiX**?Under the same configuration, the deployment of instant-ngp is successful.

cmake：3.25.0
cuda：11.8
Optix：8.0
gpu：3090 24G

(nerf) lh@omnisky:~/repo2/lh/code/lh/4.NRC/NeuS2$ cmake --build build --config RelWithDebInfo -j
[ 25%] Built target optix_program
[ 31%] Built target glfw_objects
[ 51%] Built target tiny-cuda-nn
[ 53%] Building CUDA object CMakeFiles/ngp.dir/src/triangle_bvh.cu.o
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/optix/program.h(75): error: identifier "optixModuleCreateFromPTX" is undefined
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(664): here

/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/optix/program.h(144): error: class "OptixPipelineLinkOptions" has no member "debugLevel"
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(664): here

/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/optix/program.h(159): error: too few arguments in function call
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(664): here

3 errors detected in the compilation of "/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu".
CMakeFiles/ngp.dir/build.make:386: recipe for target 'CMakeFiles/ngp.dir/src/triangle_bvh.cu.o' failed
make[2]: *** [CMakeFiles/ngp.dir/src/triangle_bvh.cu.o] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/ngp.dir/all' failed
make[1]: *** [CMakeFiles/ngp.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
(nerf) lh@omnisky:~/repo2/lh/code/lh/4.NRC/NeuS2$ git submodule sync --recursive
Synchronizing submodule url for 'dependencies/neus2_tcnn'
Synchronizing submodule url for 'dependencies/neus2_tcnn/dependencies/cutlass'
Synchronizing submodule url for 'dependencies/neus2_tcnn/dependencies/fmt'
(nerf) lh@omnisky:~/repo2/lh/code/lh/4.NRC/NeuS2$ git submodule update --init --recursive
(nerf) lh@omnisky:~/repo2/lh/code/lh/4.NRC/NeuS2$ cmake --build build --config RelWithDebInfo -j
[  5%] Built target optix_program
[ 31%] Built target glfw_objects
[ 51%] Built target tiny-cuda-nn
[ 53%] Building CUDA object CMakeFiles/ngp.dir/src/triangle_bvh.cu.o
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/optix/program.h(75): error: identifier "optixModuleCreateFromPTX" is undefined
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(664): here

/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/optix/program.h(144): error: class "OptixPipelineLinkOptions" has no member "debugLevel"
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(664): here

/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/optix/program.h(159): error: too few arguments in function call
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu(664): here

3 errors detected in the compilation of "/home/lh/repo2/lh/code/lh/4.NRC/NeuS2/src/triangle_bvh.cu".
CMakeFiles/ngp.dir/build.make:386: recipe for target 'CMakeFiles/ngp.dir/src/triangle_bvh.cu.o' failed
make[2]: *** [CMakeFiles/ngp.dir/src/triangle_bvh.cu.o] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/ngp.dir/all' failed
make[1]: *** [CMakeFiles/ngp.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 19reborn** [comment]
Hi @luh0502, the optix problem can be solved as shown in https://github.com/19reborn/NeuS2/issues/5.

**Comment by 19reborn** [comment]
For the compiling error of neus2_tcnn, could you please re-check the codes in network.cu(114)? The lateset correct codes should be 
```
#if TCNN_MIN_GPU_ARCH > 70
		uint32_t n_neurons = network.value("n_neurons", 128u);
		switch (n_neurons) {
			case  16: return FullyFusedMLP<network_precision_t,  16>::REQUIRED_ALIGNMENT();
			case  32: return FullyFusedMLP<network_precision_t,  32>::REQUIRED_ALIGNMENT();
			case  64: return FullyFusedMLP<network_precision_t,  64>::REQUIRED_ALIGNMENT();
			case 128: return FullyFusedMLP<network_precision_t, 128>::REQUIRED_ALIGNMENT();
			default: throw std::runtime_error{std::string{"FullyFusedMLP only supports 16, 32, 64, and 128 neurons, but got "} + std::to_string(n_neurons) + ". Use CutlassMLP instead if this is a requirement."};
		}
#else
		throw std::runtime_error{"FullyFusedMLP was not compiled due to insufficient GPU arch of <=70."};
#endif
```

**Comment by SWWdz** [comment]
I have changed the code, but I also get this problem.
![image](https://github.com/19reborn/NeuS2/assets/104372768/e8b7dd7b-9a63-4512-8073-2792df24ce60)
![image](https://github.com/19reborn/NeuS2/assets/104372768/db2e706c-1ff7-4c51-a8cb-0379070912c0)

**Comment by 19reborn** [comment]
Hi @SWWdz, after changing the codes, the error line should be in line 116, but your error is in the line 114. Could you please try removing the build directory and using cmake to compile it again?

**Comment by SWWdz** [comment]
I use cmake to compile again, but I also get this problem.
I use CUDA 11.3; cmake：3.27.0; gpu：TITAN xp  12G
![image](https://github.com/19reborn/NeuS2/assets/104372768/9d3db42a-a848-4004-86a3-c2851d979cb3)

**Comment by SWWdz** [comment]
I also get this problem when I delete build directory and run it again. The codes are behind. Can you give me some advice? Thanks!








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "19reborn/NeuS2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月31日(星期四) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [19reborn/NeuS2]  error: identifier "FullyFusedMLP" is undefined (Issue #15)





 
Hi @SWWdz, after changing the codes, the error line should be in line 116, but your error is in the line 114. Could you please try removing the build directory and using cmake to compile it again?

**Comment by Luh1124** [comment]
> For the compiling error of neus2_tcnn, could you please re-check the codes in network.cu(114)? The correct codes should be
> 
> ```
> #if TCNN_MIN_GPU_ARCH > 70
> 		uint32_t n_neurons = network.value("n_neurons", 128u);
> 		switch (n_neurons) {
> 			case  16: return FullyFusedMLP<network_precision_t,  16>::REQUIRED_ALIGNMENT();
> 			case  32: return FullyFusedMLP<network_precision_t,  32>::REQUIRED_ALIGNMENT();
> 			case  64: return FullyFusedMLP<network_precision_t,  64>::REQUIRED_ALIGNMENT();
> 			case 128: return FullyFusedMLP<network_precision_t, 128>::REQUIRED_ALIGNMENT();
> 			default: throw std::runtime_error{std::string{"FullyFusedMLP only supports 16, 32, 64, and 128 neurons, but got "} + std::to_string(n_neurons) + ". Use CutlassMLP instead if this is a requirement."};
> 		}
> #else
> 		throw std::runtime_error{"FullyFusedMLP was not compiled due to insufficient GPU arch of <=70."};
> #endif
> ```

感谢，我按照https://github.com/19reborn/NeuS2_TCNN/blob/d3a12b91097ddca15f17b1b6dbacb36fa0c768b2/src/network.cu手动修改了network.cu的内容，现在可以编译成功了。

**Comment by Luh1124** [comment]
但是我在安装Optix之后重新编译遇到了新的问题：
(nerf) luh@lihong:~/repo1/repo_8T/code/1.nerf/NeuS2$ cmake . -B build
-- Targeting GPU architectures: 61;61
CMake Warning at dependencies/neus2_tcnn/CMakeLists.txt:114 (message):
  Fully fused MLPs do not support GPU architectures of 70 or less.  Falling
  back to CUTLASS MLPs.  Remove GPU architectures 70 and lower to allow
  maximum performance


-- Using X11 for window creation
-- OptiX_INSTALL_DIR value: /usr/local/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64
CMake Deprecation Warning at dependencies/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- pybind11 v2.7.1 
-- Configuring done (0.3s)
-- Generating done (0.3s)
-- Build files have been written to: /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/build
(nerf) luh@lihong:~/repo1/repo_8T/code/1.nerf/NeuS2$ cmake --build build --config RelWithDebInfo -j 
[  5%] Built target optix_program
[ 32%] Built target glfw_objects
[ 50%] Built target tiny-cuda-nn
[ 52%] Building CUDA object CMakeFiles/ngp.dir/src/triangle_bvh.cu.o
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/optix/program.h(75): error: identifier "optixModuleCreateFromPTX" is undefined
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(664): here

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/optix/program.h(144): error: class "OptixPipelineLinkOptions" has no member "debugLevel"
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(664): here

/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/optix/program.h(159): error: too few arguments in function call
          detected during:
            instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Program<ngp::Raystab>, _Args=<const char *, unsigned long, OptixDeviceContext &>]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(635): here
            instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemory<ngp::Triangle> &, cudaStream_t) [with BRANCHING_FACTOR=4U]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(647): here
            instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" 
/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(664): here

3 errors detected in the compilation of "/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu".
make[2]: *** [CMakeFiles/ngp.dir/build.make:387: CMakeFiles/ngp.dir/src/triangle_bvh.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:201: CMakeFiles/ngp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by 19reborn** [comment]
Hi @Luh1124, you may need to degrade the optix version to 7.6 as shown in https://github.com/19reborn/NeuS2/issues/5.

**Comment by Luh1124** [comment]
> But I encountered new issues after installing Optix and attempting to recompile.
> 
> (nerf) luh@lihong:~/repo1/repo_8T/code/1.nerf/NeuS2$ cmake . -B build -- Targeting GPU architectures: 61;61 CMake Warning at dependencies/neus2_tcnn/CMakeLists.txt:114 (message): Fully fused MLPs do not support GPU architectures of 70 or less. Falling back to CUTLASS MLPs. Remove GPU architectures 70 and lower to allow maximum performance
> 
> -- Using X11 for window creation -- OptiX_INSTALL_DIR value: /usr/local/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64 CMake Deprecation Warning at dependencies/pybind11/CMakeLists.txt:8 (cmake_minimum_required): Compatibility with CMake < 3.5 will be removed from a future version of CMake.
> 
> Update the VERSION argument value or use a ... suffix to tell CMake that the project does not need compatibility with older versions.
> 
> -- pybind11 v2.7.1 -- Configuring done (0.3s) -- Generating done (0.3s) -- Build files have been written to: /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/build (nerf) luh@lihong:~/repo1/repo_8T/code/1.nerf/NeuS2$ cmake --build build --config RelWithDebInfo -j [ 5%] Built target optix_program [ 32%] Built target glfw_objects [ 50%] Built target tiny-cuda-nn [ 52%] Building CUDA object CMakeFiles/ngp.dir/src/triangle_bvh.cu.o /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/optix/program.h(75): error: identifier "optixModuleCreateFromPTX" is undefined detected during: instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Programngp::Raystab, _Args=<const char *, unsigned long, OptixDeviceContext &>]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(635): here instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemoryngp::Triangle &, cudaStream_t) [with BRANCHING_FACTOR=4U]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(647): here instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(664): here
> 
> /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/optix/program.h(144): error: class "OptixPipelineLinkOptions" has no member "debugLevel" detected during: instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Programngp::Raystab, _Args=<const char *, unsigned long, OptixDeviceContext &>]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(635): here instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemoryngp::Triangle &, cudaStream_t) [with BRANCHING_FACTOR=4U]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(647): here instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(664): here
> 
> /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/optix/program.h(159): error: too few arguments in function call detected during: instantiation of "std::_MakeUniq<_Tp>::__single_object std::make_unique<_Tp,_Args...>(_Args &&...) [with _Tp=ngp::optix::Programngp::Raystab, _Args=<const char *, unsigned long, OptixDeviceContext &>]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(635): here instantiation of "void ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::build_optix(const tcnn::GPUMemoryngp::Triangle &, cudaStream_t) [with BRANCHING_FACTOR=4U]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(647): here instantiation of "ngp::TriangleBvhWithBranchingFactor<BRANCHING_FACTOR>::TriangleBvhWithBranchingFactor() [with BRANCHING_FACTOR=4U]" /home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu(664): here
> 
> 3 errors detected in the compilation of "/home/luh/repo1/repo_8T/code/1.nerf/NeuS2/src/triangle_bvh.cu". make[2]: *** [CMakeFiles/ngp.dir/build.make:387: CMakeFiles/ngp.dir/src/triangle_bvh.cu.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:201: CMakeFiles/ngp.dir/all] Error 2 make: *** [Makefile:91: all] Error 2

After deleting the build folder, you can recompile and it should work fine.

**Comment by Luh1124** [comment]
> Hi @Luh1124, you may need to degrade the optix version to 7.6 as shown in #5.

Thanks
