### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by dFuong** [19reborn/NeuS2#18]
I meet an error
![image](https://github.com/19reborn/NeuS2/assets/48349629/2441e091-9a9b-401a-b4c0-664ec8fae23a)

Please support me ?

**Comment by 19reborn** [comment]
Hi, how much VRAM does your gpu have? You can try decreasing the training batch size by adding `"batch_size": 131072` in the "hpyerparams" of the training configs (e.g. `base.json`)
