### ISSUE TITLE
It takes 30 min instead of 5 min in my 3090 GPU

### ISSUE THREAD

**Issue by Runsong123** [19reborn/NeuS2#2]
Dear author, 

thanks for your great work.
I just follow your guidance and run the following command. However, I found it take almost 30min in my 3090 GPU. I am wondering whether I need to change something to keep the consistency with your paper setting?

![image](https://github.com/19reborn/NeuS2/assets/39645074/cc8f3d50-92e5-4653-b3b3-6536b7ed2be0)

`python scripts/run.py --mode sdf --scene ./data/DTU_scan24/transform.json --name dtu_neus2` (Here I just download the data from the given link and place it in the data dir)

Looking forward to your reply! Many thanks in advance!

Bests,
Runsong

**Comment by erin47** [comment]
Hi, you can specify the number of training iterations by adding `--n_steps` param in the script. Or, you can use `scripts/run_dynamic.py` and specify the number in the config file.

For static scene reconstruction, we train our model for ~15k iterations, as demonstrated in our supplementary document.

Thank you for your interest in our work!

**Comment by Runsong123** [comment]
Got it. Thanks so much for your kind reply!

Bests,
Runsong
