### ISSUE TITLE
transform_matrix calculation 

### ISSUE THREAD

**Issue by wuyingxiong** [19reborn/NeuS2#21]
Thanks for your work！
          How do you calculate the transform_matrix by using the original data etc:extrinsic？
          It seems that the inverse matrix is calculated，but it is not correct in T. 
          Could you upload the transformation script?
          "transform_matrix": 
                    0.9702627062797546,-0.01474287360906601,-0.2416049838066101,0.9490470290184021
		    0.0074799139983952045,0.9994929432868958,-0.0309509988874197,0.052045613527297974
                    0.2419387847185135,0.028223415836691856, 0.9698809385299683,-2.6711924076080322
                    0.0,0.0,0.0,1.0
            extrinsic
                    0.970263 0.00747983 0.241939 -191.02
                    -0.0147429 0.999493 0.0282234 3.28832
                    -0.241605 -0.030951 0.969881 22.5401
                    0.0 0.0 0.0 1.0

**Comment by abhishekmonogram** [comment]
On that note, @19reborn can you please upload the dataset creation code from videos? A script that can take in colmap images and cameras and generate the transform.json. Whenever I have tried using my custom dataset, the reconstructions have failed whereas when I have used the available synthetic data, the reconstructions have been terrific. I think the transform.json might be incorrect in the way, I have been generating them.

**Comment by erin47** [comment]
Hi,
The "transform_matrix" is the camera pose in world space (i.e. the camera2world transformation matrix, also the inverse of extrinsic).
btw, NeuS2 also supports data format provided by Instant-NGP, maybe you can try this as well.

**Comment by 19reborn** [comment]
hi @wuyingxiong , We use meters as T's unit. You may need to first scale the T according to the unit and then do the inverse operation.

**Comment by 19reborn** [comment]
hi @abhishekmonogram , you can follow instant-ngp (https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md) to generate the transform.json from colmap.

**Comment by VerseWei** [comment]
@19reborn @wuyingxiong @abhishekmonogram @erin47 @AuthorityWang 
Hello，
I use the instant - NGP (https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md The generated transform.json has only transform_matrix but has no intrinsic_matrix. How can I fix this?
