### ISSUE TITLE
how to improve the quality?

### ISSUE THREAD

**Issue by zf-666** [19reborn/NeuS2#25]
Thank you for your great work! I have recently tried it on my dataset using the **dtu.json** file, but unfortunately, the results were not good. Could you please provide me with some advice on how to adjust the parameters to improve the performance?
![image](https://github.com/19reborn/NeuS2/assets/60997009/bb700b1b-405d-4b43-92b3-ed9a5d4669e3)

**Comment by 19reborn** [comment]
Hi @zf-666 , How many views do you have for training? NeuS2 requires dense input views (e.g. 40~50 views) to get the best performance. You can try increasing the `ek_loss_weight` in the training config to get more smooth results.
