### ISSUE TITLE
sphere init in your tcnn

### ISSUE THREAD

**Issue by adkAurora** [19reborn/NeuS2#29]
How to Initialize neus2-tcnn "FullyFusedMLP"  to approximately represent a sphere? In your project "sdf_bias" is setted as -0.1, what's this mean ?

**Comment by 19reborn** [comment]
Hi @adkAurora, we first randomize a set of MLP weights in Pytorch (`utils/mlp_weights.txt`), which are stored in utils/mlp_weights.txt, and then we directly load these weights into the "FullyFusedMLP".  Since 'FullyFusedMLP' is designed in the form of `y=Ax` rather than `y=Ax+b`, we need to introduce an additional parameter called `sdf_bias` to the MLP's final layer. This modification is necessary to fully implement the geometry initialization as outlined in [IGR](https://arxiv.org/abs/2002.10099). 
The radius of the initialized sphere can be controlled by the `sdf_bias`.

**Comment by adkAurora** [comment]
> 
Has "sdf_bias" is incorporated into the FullyFusedMLP code of 'neus2-tcnn'. or Do I need to manually process the output of the MLP?

**Comment by 19reborn** [comment]
Hi @adkAurora , you can adjust this in the training configuration of NeuS2, specifically in reference to `sdf_bias`.

**Comment by adkAurora** [comment]
> Hi @adkAurora , you can adjust this in the training configuration of NeuS2, specifically in reference to `sdf_bias`.

I'm sorry for any misunderstanding earlier. I aspire to use your neus2-tcnn to accelerate my own sdf network as I think the implementation of the second-order derivative in fullyfusedmlp is brilliant. I tried to directly swap the earlier tcnn with neus2-tcnn but the resultant training outcomes weren't satisfactory.As per your suggestion, I also attempted to initialize the weights using a txt file, but the result was still not up to par. After loading the weights, the sdf obtained from training the fullyfusedmlp network didn't form a sphere. Here are two images for reference. The first one is the normal result, and the second one is the result after replacing the fullyfusedmlp.
![image](https://github.com/19reborn/NeuS2/assets/30972697/f2a1b3fd-e539-4c55-8023-0d82770a2784)
![image](https://github.com/19reborn/NeuS2/assets/30972697/82647070-4276-4e8f-8470-89da45f2186f)

**Comment by 19reborn** [comment]
Hi, have you appended the original xyz with the hash encoding as the MLP's input?

**Comment by adkAurora** [comment]
yes 

encoding = tcnn.Encoding(n_input_dims, config_to_primitive(config))
encoding = CompositeEncoding(encoding, include_xyz=config.get('include_xyz', False), xyz_scale=2., xyz_offset=-1.)

**Comment by 19reborn** [comment]
Hi, do you align the input with the weights，e.g. make sure whether xyz is in front of the hash grid or not? Also, what do the `xyz_scale` and `xyz_offset` mean in your codes?

**Comment by adkAurora** [comment]
Yes, the only change I made was to replace the earlier fullyfuedmlp with yours, which couldn't handle second-order derivatives.

**Comment by 19reborn** [comment]
Hi, is it possible for you to send your code for testing the geometry intialization to me (w752531540@gmail.com)?
