### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by fatbao55** [19reborn/NeuS2#3]
Dear authors, 

Thanks for the great work!

I ran `python scripts/run.py --mode nerf --scene ../data/dtu_scan24/transform.json --name dtu_neus --network  --n_steps 15000` but the predicted image after 15k iterations doesn't seem to make sense, and the generated mesh is 0kb. 

![frame_000000_pred](https://github.com/19reborn/NeuS2/assets/128988660/a904646b-93d8-42f3-81bd-87137ddcfaf0)

It works when I run `./build/testbed --scene data/dtu_scan24//transform.json` but not with the python bindings. The results in the GUI after 15k train steps is also not ideal.
![Screenshot from 2023-08-17 12-25-15](https://github.com/19reborn/NeuS2/assets/128988660/234c5631-b783-4780-a3b3-37e3037568d0)

I was wondering if (1) there is an error in the python bindings and (2) how many iterations is needed?

**Comment by erin47** [comment]
Hi, when you run python bindings you need to specify the network configuration (which we provide an example in the data for your reference) by the `--network` param, or by default the base config is set.

Also, you can specify the config by `--config ${config_path}` for the GUI running, like `./build/testbed --scene data/dtu_scan24//transform.json --config data/dtu_scan24/config.json`. (the default lr is 1e-3, while the lr for DTU scan24 is 1e-2).

btw, you could change the view of the GUI rendering result (the current view is at the back of the scene) and check the mesh.

**Comment by fatbao55** [comment]
@erin47 Thanks for your advice!

https://github.com/19reborn/NeuS2/blob/ac433feff4aa74d6c6d278578babd1345bd2256f/scripts/run.py#L85-L87

Previously `--network ` already reads in `configs/nerf/base.json` due to the above lines of code. 

I modified the script to make sure I was pointing to right config file, it gave me the same result:
- `python scripts/run.py --mode nerf --scene ../data/dtu_scan24/transform.json --name dtu_neus --network=configs/nerg/base.json  --n_steps 15000`

When I modified the script to this:
- `python scripts/run.py --mode nerf --scene ../data/dtu_scan24/transform.json --name dtu_neus --network=data/dtu_scan24/config.json  --n_steps 15000`
I encountered this error `XX/NeuS2/dependencies/neus2_tcnn/include/tiny-cuda-nn/gpu_memory.h:573 cudaDeviceSynchronize() failed with error an illegal memory access was encountered`. I am training on RTX3090 GPU.


Do you have any advice on how to resolve this? and may I check what device are you training on?

**Comment by erin47** [comment]
I am sorry for my misleading. The configuration path should be absolute path. Or, you can copy the config file into the “configs/nerf/” directory, and point to the filename only.

**Comment by fatbao55** [comment]
Hi @erin47 , inputting the abs path for `configs/nerf/base.json` works, thanks so much! 

However, I still encounter `XX/NeuS2/dependencies/neus2_tcnn/include/tiny-cuda-nn/gpu_memory.h:573 cudaDeviceSynchronize() failed with error an illegal memory access was encountered` when I attempt to run with `data/dtu_scan24/config.json`. 

The line in the config that throws this error is removing `"predict_global_movement": true,`. Do you have any advice on how to resolve this? and may I check what device are you training on?

**Comment by 19reborn** [comment]
Hi @fatbao55, thanks for reviewing and catching that mistake. There exists a bug when `"predict_global_movement": false`, and we will fix it soon. You can now add `"predict_global_movement": true` in `data/dtu_scan24/config.json` and check the performance. It should not impact the performance of static scene reconstruction.

Also, we just run the code on a V100 GPU and it works.

**Comment by fatbao55** [comment]
@19reborn Sure, thanks for clarifying. I am able to run with `data/dtu_scan24/config.json` when I add `predict_global_movement": true`.
