### ISSUE TITLE
Dynamic scene, memory and color

### ISSUE THREAD

**Issue by drperpen** [19reborn/NeuS2#30]
Hi,
I am running a 200 frames dynamic scene with 140 images/cameras of res 3840x2160. My GPU has 26Gb, and it could only handle the first frame before running out of memory. I halved the resolution and it did 20 frames before running out of memory. I am assuming this is the expected behavior, as it keeps in memory previous results. My first question is, if I run it frame by frame instead to avoid the memory issue `run_per_frame.py`, will the mesh reconstructions look as smooth as with `run_dynamic.py`? (Assuming a no here :) )

The second question is regarding the color, during the 20 frames that ran, the colors progressively get noisier as the shape changes. Then If I do another job starting from frame 21, the colors seem fine again.

On the other hand the mesh during those 20 frames looks really good and the shape/topology transition from frame to frame, looks dramatically better that any other off the shelf multi view reconstruction system I have tried. Good job!

**Comment by 19reborn** [comment]
Hi @drperpen , I think `run_per_frame.py` can get similar results. However, it will increase the training time compared with `run_per_frame.py` and may fail in training if the objecj moves out of the bbox.

It's strange that the color gets noisier. Could you please show more details?
