### ISSUE TITLE
Failed on custom dataset 

### ISSUE THREAD

**Issue by blacksino** [19reborn/NeuS2#31]
<img width="554" alt="截屏2023-09-08 17 10 45" src="https://github.com/19reborn/NeuS2/assets/44363764/6c22b0ab-aced-4d20-91ee-a15bbe4ceb7d">
你好，我在自己的数据集上测试了一下发现结果不太理想，transform.json是直接使用colmap算出来的，config是使用默认的base
<img width="1233" alt="image" src="https://github.com/19reborn/NeuS2/assets/44363764/e263ee65-ba61-43fa-94f8-202bdaa4cd94">
请问我该如何改进呢？

**Comment by blacksino** [comment]
https://github.com/19reborn/NeuS2/assets/44363764/4cba0c9e-5bef-41fc-a09b-db6020b0e1f3

**Comment by 19reborn** [comment]
Hi @blacksino , you can try using the neuspp branch since your data doesn't have background masks.

**Comment by blacksino** [comment]
just tries neuspp branch and the results still looks terrible...
I used womask.json as default.
<img width="1115" alt="截屏2023-09-11 11 11 37" src="https://github.com/19reborn/NeuS2/assets/44363764/e8457b68-7e9a-4d42-aa23-ee6d390044b1">
mask_loss seems to be the problem,maybe I should provide the mask ?

**Comment by blacksino** [comment]
by the image,the rendered image has four channels,and ref image wo mask has three channels,so there will some mistakes in line 355in /scripts/render_utils.py

**Comment by 19reborn** [comment]
> just tries neuspp branch and the results still looks terrible... I used womask.json as default. <img alt="截屏2023-09-11 11 11 37" width="1115" src="https://user-images.githubusercontent.com/44363764/266898032-e8457b68-7e9a-4d42-aa23-ee6d390044b1.png"> mask_loss seems to be the problem,maybe I should provide the mask ?

Hi, have you set the  `aabb_scale` to 1 in your transform.json?

**Comment by blacksino** [comment]
yes I have, I have add "aabb_scale": 1.0,
    "scale": 0.5,
    "offset": [
        0.5,
        0.5,
        0.5
    ], to transform.json generated by colmap.
here is the diff image,only a small part of image has been rendered
<img width="369" alt="截屏2023-09-11 16 07 19" src="https://github.com/19reborn/NeuS2/assets/44363764/8203015d-4a2b-4784-afdb-813110d094f3">

**Comment by 19reborn** [comment]
Hi @blacksino , it seems that the object is not in the AABB. You need to modify the `scale` and `offset` to move it into the aabb (which can be visualized using the GUI mode).

**Comment by kllgjc** [comment]
> Hi @blacksino , it seems that the object is not in the AABB. You need to modify the `scale` and `offset` to move it into the aabb (which can be visualized using the GUI mode).

I'm having some troble with this, how do you use the GUI to make sure the bounding box is around the object? or, how do you use the gui in general?

**Comment by 19reborn** [comment]
Hi @kllgjc , you can visualize the cameras and the aabb in the GUI. We just approximate the object's position using the visualized cameras.

**Comment by blacksino** [comment]
> Hi @blacksino , it seems that the object is not in the AABB. You need to modify the `scale` and `offset` to move it into the aabb (which can be visualized using the GUI mode).

I run NeuS2 on remote server, any better methods to determine 'scale' and 'offset', many thanks

**Comment by blacksino** [comment]
在ngp最新的commit中，脚本colmap2nerf有一段代码：
`	if args.keep_colmap_coords:
		flip_mat = np.array([
			[1, 0, 0, 0],
			[0, -1, 0, 0],
			[0, 0, -1, 0],
			[0, 0, 0, 1]
		])

		for f in out["frames"]:
			f["transform_matrix"] = np.matmul(f["transform_matrix"], flip_mat) # flip cameras (it just works)
	else:
		# don't keep colmap coords - reorient the scene to be easier to work with

		up = up / np.linalg.norm(up)
		print("up vector was", up)
		R = rotmat(up,[0,0,1]) # rotate up vector to [0,0,1]
		R = np.pad(R,[0,1])
		R[-1, -1] = 1

		for f in out["frames"]:
			f["transform_matrix"] = np.matmul(R, f["transform_matrix"]) # rotate up to be the z axis

		# find a central point they are all looking at
		print("computing center of attention...")
		totw = 0.0
		totp = np.array([0.0, 0.0, 0.0])
		for f in out["frames"]:
			mf = f["transform_matrix"][0:3,:]
			for g in out["frames"]:
				mg = g["transform_matrix"][0:3,:]
				p, w = closest_point_2_lines(mf[:,3], mf[:,2], mg[:,3], mg[:,2])
				if w > 0.00001:
					totp += p*w
					totw += w
		if totw > 0.0:
			totp /= totw
		print(totp) # the cameras are looking at totp
		for f in out["frames"]:
			f["transform_matrix"][0:3,3] -= totp

		avglen = 0.
		for f in out["frames"]:
			avglen += np.linalg.norm(f["transform_matrix"][0:3,3])
		avglen /= nframes
		print("avg camera distance from origin", avglen)
		for f in out["frames"]:
			f["transform_matrix"][0:3,3] *= 4.0 / avglen # scale to "nerf sized"

	for f in out["frames"]:
		f["transform_matrix"] = f["transform_matrix"].tolist()`
通过这段代码，我是否可以直接对相机外参进行变换，而不需要自己手动的根据gui的可视化效果，手动的调整offet和scale呢

**Comment by 19reborn** [comment]
> 在ngp最新的commit中，脚本colmap2nerf有一段代码： ` else: # don't keep colmap coords - reorient the scene to be easier to work with
> 
> ```
> 	up = up / np.linalg.norm(up)
> 	print("up vector was", up)
> 	R = rotmat(up,[0,0,1]) # rotate up vector to [0,0,1]
> 	R = np.pad(R,[0,1])
> 	R[-1, -1] = 1
> 
> 	for f in out["frames"]:
> 		f["transform_matrix"] = np.matmul(R, f["transform_matrix"]) # rotate up to be the z axis
> 
> 	# find a central point they are all looking at
> 	print("computing center of attention...")
> 	totw = 0.0
> 	totp = np.array([0.0, 0.0, 0.0])
> 	for f in out["frames"]:
> 		mf = f["transform_matrix"][0:3,:]
> 		for g in out["frames"]:
> 			mg = g["transform_matrix"][0:3,:]
> 			p, w = closest_point_2_lines(mf[:,3], mf[:,2], mg[:,3], mg[:,2])
> 			if w > 0.00001:
> 				totp += p*w
> 				totw += w
> 	if totw > 0.0:
> 		totp /= totw
> 	print(totp) # the cameras are looking at totp
> 	for f in out["frames"]:
> 		f["transform_matrix"][0:3,3] -= totp
> 
> 	avglen = 0.
> 	for f in out["frames"]:
> 		avglen += np.linalg.norm(f["transform_matrix"][0:3,3])
> 	avglen /= nframes
> 	print("avg camera distance from origin", avglen)
> 	for f in out["frames"]:
> 		f["transform_matrix"][0:3,3] *= 4.0 / avglen # scale to "nerf sized"
> 
> for f in out["frames"]:
> 	f["transform_matrix"] = f["transform_matrix"].tolist()`
> ```
> 
> 通过这段代码，我是否可以直接对相机外参进行变换，而不需要自己手动的根据gui的可视化效果，手动的调整offet和scale呢

Hi @blacksino , I think this idea is very great! You can have a try.

**Comment by VerseWei** [comment]
@blacksino 
Hello, As you mentioned, the rendered image has four channels, while the reference image mask has three channels, so/scripts/render_ There are some errors in utils.py. Do you know how to solve them? Thanks.

Traceback (most recent call last):
  File "/home/wxs/3D_Recon/NeuS2/scripts/run.py", line 248, in <module>
    render_img_training_view(args, testbed, log_ptr, args.scene)
  File "/home/wxs/3D_Recon/NeuS2/scripts/render_utils.py", line 338, in render_img_training_view
    diffimg = np.absolute(image - ref_image)
ValueError: operands could not be broadcast together with shapes (1280,720,4) (1280,720,3)

**Comment by blacksino** [comment]
you could modify corresponding code snippet.

**Comment by yuedajiong** [comment]
I tested on my custom dataset, the output mesh is not good, even the coarse shape.  it looks the normals is not  correct.   :-(
