### ISSUE TITLE
CMake Build error!!!!

### ISSUE THREAD

**Issue by VerseWei** [19reborn/NeuS2#32]
(base) wxs@cvrs:~/3D_Projects/NeuS2$ cmake --build build --config RelWithDebInfo -j
[ 28%] Built target glfw_objects
[ 50%] Built target tiny-cuda-nn
[ 92%] Built target ngp
[ 96%] Built target testbed
[ 98%] Building CUDA object CMakeFiles/pyngp.dir/src/python_api.cu.o
/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(448): error: pointer to incomplete class type "_frame" is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(448): error: type name is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(448): error: expected an expression

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(450): error: pointer to incomplete class type "_frame" is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(450): error: type name is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(450): error: expected an expression

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/detail/type_caster_base.h(451): error: pointer to incomplete class type "_frame" is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/pybind11.h(2163): error: class "_ts" has no member "frame"

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/pybind11.h(2164): error: pointer to incomplete class type "_frame" is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/pybind11.h(2165): error: pointer to incomplete class type "_frame" is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/pybind11.h(2168): error: pointer to incomplete class type "_frame" is not allowed

/home/wxs/3D_Projects/NeuS2/dependencies/pybind11/include/pybind11/pybind11.h(2168): error: pointer to incomplete class type "_frame" is not allowed

12 errors detected in the compilation of "/home/wxs/3D_Projects/NeuS2/src/python_api.cu".
make[2]: *** [CMakeFiles/pyngp.dir/build.make:82：CMakeFiles/pyngp.dir/src/python_api.cu.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:227：CMakeFiles/pyngp.dir/all] 错误 2
make: *** [Makefile:103：all] 错误 2

**Comment by 19reborn** [comment]
Hi @VerseWei , do you use Python 3.11? If so, you can try using lower version, e.g. Python 3.10.

**Comment by FeiiYin** [comment]
Hi, another thing is that the environment will automatically detect the highest python version. If you want to specify which python to use for cmake, you can change `find_package(Python 3.7 COMPONENTS Interpreter Development)` to `find_package(Python 3.9 EXACT COMPONENTS Interpreter Development)` in CMakeLists.txt, which works for me.
