### ISSUE TITLE
with mask vs without mask

### ISSUE THREAD

**Issue by brianneoberson** [19reborn/NeuS2#37]
Hello,
I tested your code on my data (static scene) and it worked really well when masking the images as in the DTU dataset (using the base.json config). 
However, I tried training NeuS++ on the same data (using the neuspp branch with the womask.json config and with non-masked images) and I get really bad results. The object is not recognizable at all, just blobs.  Do you have an idea why this is happening? I am using the same transform.json in both cases and the GUI shows that the object is well centered in the bbox.

**Comment by 19reborn** [comment]
Hi @brianneoberson , this is weird. Could you share one example data you used?

**Comment by brianneoberson** [comment]
Hi, unfortunately I am not allowed to share this data. But here is one example image in the dataset and some screenshots of what it looks like in the GUI without VS with mask.
example data:
![example](https://github.com/19reborn/NeuS2/assets/43467859/e16309cd-7bf8-432a-af58-6544693283ad)
without mask:
![womask](https://github.com/19reborn/NeuS2/assets/43467859/bfd9ac3d-1768-49ba-a475-a898a02b544b)
with mask:
![wmask](https://github.com/19reborn/NeuS2/assets/43467859/5a6f2385-cff1-4142-bf90-6fb383fb7dd1)

**Comment by 19reborn** [comment]
Hi @brianneoberson , could you please try setting the SDF_GRID in line 39 of testbed_nerf.cu to 1 (rember to cmake again after the change)?

**Comment by brianneoberson** [comment]
Now it works! But actually it seems I had forgotten to cmake again after changing to the neuspp branch, because it also works without setting SDF_GRID to 1. Thanks for the help!

**Comment by 19reborn** [comment]
Great! 👍
