### ISSUE TITLE
wmask training

### ISSUE THREAD

**Issue by alvin528** [19reborn/NeuS2#39]
Impressive work! I can reproduce your results on different data.
Unlike NeuS, the mask loss weight is set to 0 in dtu.json. I wonder how mask training is guaranteed in this work? Could you explain it in general? I'm not familiar with cuda code and it would be nice to point out where it is implemented. Thanks!

**Comment by 19reborn** [comment]
Hi @alvin528 , thanks for using our code. We follow Instant-ngp to use a random background color trick. You can refer to https://github.com/NVlabs/instant-ngp/discussions/192 for more details.

**Comment by alvin528** [comment]
Thank you for your reply!
