### ISSUE TITLE
Wrong result on FOX dataset from Instant-NGP.

### ISSUE THREAD

**Issue by lshwan** [19reborn/NeuS2#49]
Thank you for sharing such a great work!

I'm testing NeuS2 on Fox dataset given by Instant-NGP official repository [fox dataset](https://github.com/NVlabs/instant-ngp/tree/master/data/nerf/fox).

As NeuS2 shares data format with Instant-NGP, I expected that it could reconstruct complete fox face.
But after running, NeuS2 gave 3D model shown in the image below.

![image](https://github.com/19reborn/NeuS2/assets/67103334/800da874-82e9-4e48-a038-e2cffb0af727)

I used same model config as dtu.json.

Are there anything I missed about the data preparation or coordinates transformation?

Thanks!

**Comment by 19reborn** [comment]
Hi @lshwan , the fox dataset doesn't contain mask for training, so it would be better to use the `neuspp` branch.
