### ISSUE TITLE
Optix 8.0 doesn't work - stick with 7.6!

### ISSUE THREAD

**Issue by MikePelton** [19reborn/NeuS2#5]
Very excited to see the code here - thanks you! Not an issue, more an observation - if you install the latest OptiX on Windows you'll get 8.0 and that causes some issues with this code; I just regressed to OptiX 7.6 and the C++ side all builds beautifully.

**Comment by 19reborn** [comment]
@MikePelton Thanks for the observation! Actually NeuS2 doesn't use OptiX for implementation. It's only inherited from Instant-NGP's code and we will consider remove this dependency.
