### ISSUE TITLE
dynamic synthetic scenes

### ISSUE THREAD

**Issue by tb2-sy** [19reborn/NeuS2#57]
Thanks for your nice work! The paper introduces the dynamic datasets and mentions three Synthetic Scenes and Real Scenes, but you only provide one example scene for download. How can I find these datasets you mentioned, such as dynamic lego?

**Comment by decai-chen** [comment]
@tb2-sy Hey, I cannot find the dynamic multiview lego dataset either. Did you manage to get the dataset? Thanks
