### ISSUE TITLE
Unbounded scenes? 

### ISSUE THREAD

**Issue by antithing** [19reborn/NeuS2#6]
Hi! Thank you for making this code available.
Will this approach work on unbounded scenes such as the mipNerf360 dataset?

**Comment by erin47** [comment]
Hi, sorry that our method currently only supports masked scenes. The unbounded scenes may result in undesired surfaces in the background.

**Comment by erin47** [comment]
Hi,
UPDATE! you can now use code from neuspp branch for unbounded scene reconstruction.

**Comment by Pixie8888** [comment]
> Hi, sorry that our method currently only supports masked scenes. The unbounded scenes may result in undesired surfaces in the background.

Hi,

What is "masked scene"? Does NeuS2 works on ScanNet scene reconstruction?
