### ISSUE TITLE
Color gets worse in training

### ISSUE THREAD

**Issue by xmeng525** [19reborn/NeuS2#60]
Dear authors,
Thank you for the great work. I have a question about the color of exported mesh.
I tried to reconstruct a sphere with 26 viewpoints. Here are 4 example views of the input.
![000023](https://github.com/19reborn/NeuS2/assets/25536317/315a76e7-eaee-4042-b7a7-dcf7c226d910)![000018](https://github.com/19reborn/NeuS2/assets/25536317/444cbc63-3add-4da1-8dc3-468486acdf69)![000008](https://github.com/19reborn/NeuS2/assets/25536317/78d051cd-b6a3-411c-84f0-13c01b718ef5)![000000](https://github.com/19reborn/NeuS2/assets/25536317/aa3e313e-d780-4b13-9cdb-592db269f7f8)

In the training process, everything loos normal (the RGB loss and the eikonal loss decreases; the geometry get better; and the rendered images look good). However, I get more and more noise in the vertex color of the exported mesh as shown below.
Epoch = 500
![ep50003](https://github.com/19reborn/NeuS2/assets/25536317/46aa9e26-ac48-4953-a16c-72edc46edae6)
Epoch = 1500 (noise starts to appear)
![ep150004](https://github.com/19reborn/NeuS2/assets/25536317/063e680e-7063-4699-9620-f4571c93003e)
Epoch = 3000 (the colors becomes dark and gloomy)
![ep300005](https://github.com/19reborn/NeuS2/assets/25536317/caadfdb9-2af6-4b87-84fb-2173d168389c)

Have you observed similar phenomenon in your experiments? Do you have any clue about the reasons?

**Comment by xmeng525** [comment]
[sphere.zip](https://github.com/19reborn/NeuS2/files/14391384/sphere.zip)
I have attached the dataset in case you would like to take a look. The configuration file I used is configs/nerf/base.json.
Thanks!

**Comment by 19reborn** [comment]
Hi @xmeng525 , thanks for using our codes! I guess the main reason is that the image resolution is too low (64x64).

**Comment by xmeng525** [comment]
Thank you for answering. Looking forward to seeing more great work from U!
