### ISSUE TITLE
How to use mask in custom dataset?

### ISSUE THREAD

**Issue by j-cyoung** [19reborn/NeuS2#62]
Thanks for your amazing work! However I encountered some problems during test on my custom dataset.
I tried different ways to reconstruct object from images with mask, but always failed. I use the format of instant-ngp:
1. I add additional channel (alpha channel) on my images. The channel values are either 255 or 0. However the result is unexpected. I first run `colmap2nerf.py` script provided by `instant-ngp`, and then substract the area of interests from the images (applying the predicted mask on the original images) to get 4 channels images to replace the original images.

[Training Data]
![0011](https://github.com/19reborn/NeuS2/assets/54196410/4a26db9f-c1fd-48ca-b166-6a0571733b77)

[Mesh]
![image](https://github.com/19reborn/NeuS2/assets/54196410/f532106d-8da7-46da-9808-84b5a0c226d9)

2. I add the mask files with the specific name into the `images` directory, just as the notes mentioned in `instant-ngp`(https://github.com/NVlabs/instant-ngp#:~:text=Q%3A%20How%20to,indicate%20masked%2Daway%20regions)

![image](https://github.com/19reborn/NeuS2/assets/54196410/50811b26-f179-4842-8f5a-0bc3711528b4)

However the result is also unexpected. The size of `mesh.obj` file is 0 bytes. I guess the algorithm won't read the specific name of mask files and struggle to manage the photos with background.

I'm trying to read the source code, which may take some time cause I'm not familiar with the cuda code. So is there a way to apply the mask ? Thanks so much : )

**Comment by j-cyoung** [comment]
The paremeter `aabb_scale` matters. Just use the small number (e.g. 2).

**Comment by oguzcanbekar** [comment]
@j-cyoung Hi there, I know it's been long time but I believe so many people try to follow your steps and face same issue as me. Can you explain more detailly how did you solve this problem? I totally get similar output mesh as yours. Did you just change aabb_scale on colmap2nerf code? How did you solve your problem.. I apricate for your response.

**Comment by j-cyoung** [comment]
Yeah, I only made a change to the aabb_scale parameter in colmap2nerf. However, the code is now unreachable, so unfortunately, I am unable to provide a more detailed code implementation.
