### ISSUE TITLE
bad result with lego

### ISSUE THREAD

**Issue by brabbitdousha** [19reborn/NeuS2#75]
Hi, I tried with nerf_synthetic/lego using 50k n_steps, however, with the base.json, I didn't get results like mentioned in paper
my result:
![image](https://github.com/19reborn/NeuS2/assets/22854457/7ccd4e6d-7d46-4389-9e7e-10687c628993)

**Comment by 19reborn** [comment]
Hi @brabbitdousha , thanks for trying NeuS2! We use the config `dtu.json` of larger learning rate for the lego scene.

**Comment by brabbitdousha** [comment]
Thanks for the reply!
